version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - postgres
  mysql:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
